# Generated by Django 4.2 on 2023-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_nome_news_immagine_news_titolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='titolo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
