# Generated by Django 4.2 on 2023-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_immagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='immagine',
        ),
        migrations.AlterField(
            model_name='news',
            name='contenuto',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='titolo',
            field=models.CharField(max_length=300),
        ),
    ]
